***Array Creation: Conversion from other Python Structure***

In [1]:
import numpy as np

In [2]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
listarray.dtype

dtype('int32')

In [5]:
listarray.shape

(3, 3)

In [6]:
listarray.size

9

In [7]:
np.array({1,2,3})

array({1, 2, 3}, dtype=object)

In [8]:
zeros = np.zeros((2,5))

In [9]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
zeros.dtype

dtype('float64')

In [11]:
range = np.arange(15)

In [12]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
lspace1 = np.linspace(1,5,12)

In [14]:
lspace1

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [15]:
lspace2 = np.linspace(1,5,5)

In [16]:
lspace2

array([1., 2., 3., 4., 5.])

In [17]:
emp = np.empty((4,6))

In [18]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.78021663e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.24610383e-306,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 8.45590539e-307,
        6.23054972e-307, 8.45593934e-307, 8.34451079e-308]])

In [19]:
emp_like = np.empty_like(lspace2)

In [20]:
emp_like

array([1., 2., 3., 4., 5.])

In [21]:
ide = np.identity(45)

In [22]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [23]:
ide.shape

(45, 45)

In [24]:
arr = np.arange(90)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [26]:
arr.reshape(3,30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [27]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [28]:
arr.shape

(90,)

In [29]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [30]:
ar = np.array(x)

In [31]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
ar.sum(axis=0)

array([12, 15, 18])

In [33]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [34]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [35]:
ar.flat

In [36]:
for item in ar.flat:
    print(item)


1
2
3
4
5
6
7
8
9


In [37]:
ar.ndim

2

In [38]:
ar.size

9

In [39]:
ar.nbytes

36

In [40]:
one = np.array([1,50,500,200,4])

In [41]:
one.argmax()

2

In [42]:
one.argmin()

0

In [43]:
one.argsort()

array([0, 4, 1, 3, 2], dtype=int64)

In [44]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
ar.argmin()

0

In [46]:
ar.argmax()

8

In [47]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [48]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [49]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [50]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [51]:
ar.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [52]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
ar1 = np.array([[1, 6, 3],
                [4, 0, 6],
                [7, 2, 9]])

In [55]:
ar + ar1

array([[ 2,  8,  6],
       [ 8,  5, 12],
       [14, 10, 18]])

In [56]:
(ar + ar1).T

array([[ 2,  8, 14],
       [ 8,  5, 10],
       [ 6, 12, 18]])

In [57]:
[33,64]+[24,54]

[33, 64, 24, 54]

In [58]:
ar * ar1

array([[ 1, 12,  9],
       [16,  0, 36],
       [49, 16, 81]])

In [59]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [60]:
ar.sum()

45

In [61]:
ar.max()

9

In [62]:
ar.min()

1

In [63]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [65]:
type(np.where(ar>5))

tuple

In [66]:
np.count_nonzero(ar)

9

In [67]:
import sys

In [68]:
py_ar = [0,3,22,5]

In [69]:
np_ar = np.array(py_ar)

In [70]:
sys.getsizeof(1) * len(py_ar)

112

In [71]:
np_ar.itemsize * np_ar.size

16