# 1-D Array

In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2, 3])

In [3]:
a

array([0, 1, 2, 3])

In [4]:
a.size

4

*ndim = returns number of dimension of an array*

In [5]:
a.ndim   

1

In [6]:
len(a)

4

In [7]:
a.shape

(4,)

# 2-D, 3-D Array

In [8]:
b = np.array([[0, 1, 2], [3, 4, 5]])

In [9]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
b.ndim

2

In [11]:
b.shape

(2, 3)

In [12]:
len(b)                     # returns the size of only first dimension

2

In [13]:
c = np.array([[[1],[2],[3],[4]]])

In [14]:
c

array([[[1],
        [2],
        [3],
        [4]]])

In [15]:
c.shape

(1, 4, 1)