In [1]:
import numpy as np

In [2]:
a = np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**linspace = allows you to specify the number of steps**


**arange = allows you to specify the size of the steps**

In [4]:
b = np.arange(1,10,2)          # (start , end , num_points)

In [5]:
b

array([1, 3, 5, 7, 9])

In [6]:
c = np.linspace(0,5,10)        # (start , end , num_points)

In [7]:
c

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [8]:
d = np.linspace(0,1,5, endpoint = False)

In [9]:
d

array([0. , 0.2, 0.4, 0.6, 0.8])

In [10]:
e = np.ones((3,3))

In [11]:
e

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
f = np.zeros((3,3))

In [13]:
f

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
g = np.eye(3)                  # returns identity matrix   

In [15]:
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
h = np.diag(np.array([1,2,3,4]))

In [17]:
h

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

**rand = generates sample from normal distribution**


**randn = generates sample from uniform distribution**

In [18]:
i = np.random.rand(3)

In [19]:
i

array([0.13698602, 0.32755408, 0.24399077])

In [20]:
j = np.random.randn(3,3)

In [21]:
j

array([[-0.45533551,  0.04591203,  0.57363279],
       [ 1.38396896, -0.32687523, -0.92241692],
       [ 1.07466191, -0.42123495,  1.16264007]])

In [22]:
np.random.seed(10)

In [23]:
print(np.random.randint(1,100))

10
